# Server settings
server:
  port: ${SERVER_PORT:8761}

# Basic authentication settings
schoolgrade:
  serviceRegistry:
    username: ${SERVICE_REGISTRY_USERNAME:admin}
    password: ${SERVICE_REGISTRY_PASSWORD:admin}

# Eureka settings
eureka:
  server:
    peer-node-read-timeout-ms: 60000 
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${schoolgrade.serviceRegistry.username}:${schoolgrade.serviceRegistry.password}@localhost:8761/eureka/