# Server settings
server:
  port: ${SERVER_PORT:8761}

# Spring settings
spring:
  application:
    name: service-registry

# Spring ansi settings
  output:
    ansi:
      enabled: always

# Eureka settings
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false