# Server settings
server:
  port: ${SERVER_PORT:8765}

# Eureka settings
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Spring settings
spring:
  application:
    name: api-gateway

# Spring ansi settings
  output:
    ansi:
      enabled: always

# Gateway settings
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: authuser-service
        uri: lb://authuser-service
        predicates:
        - Path=/authuser-service/**
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/course-service/**