# Spring settings
spring:
  application:
    name: notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}