# Server settings
server:
  port: ${SERVER_PORT:8087}

# Eureka settings
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Spring settings
spring:
  application:
    name: authuser-service

# Spring datasource settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:authuser}?useTimezone=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234567}

# Spring JPA settings
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

# Spring flyway settings
  flyway:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:authuser}?useTimezone=true&serverTimezone=UTC
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234567}

# Spring jackson settings
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false

# Spring ansi settings
  output:
    ansi:
      enabled: always