# Server settings
server:
  port: ${SERVER_PORT}

# Git settings 
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

# Basic authentication settings
schoolgrade:
  serviceRegistry:
    username: ${SERVICE_REGISTRY_USERNAME}
    password: ${SERVICE_REGISTRY_PASSWORD}

# Eureka settings
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}